DROP TABLE IF EXISTS `#__ropo_systems`;
 
CREATE TABLE `#__ropo_systems` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) NOT NULL DEFAULT '0',
	`regno` INT(11) NOT NULL,
	`version` INT(3) DEFAULT 0,
	`title` VARCHAR(255) NOT NULL,
	`purpose` TEXT DEFAULT NULL,
	`created_user_id` INT(11) UNSIGNED NOT NULL,
	`created_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_user_id` INT(11) UNSIGNED NOT NULL,
	`modified_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`state` ENUM('INVALID','VALID','eRECEIVED','pRECEIVED','REC_NOTIFIED','ASSIGNED','DECLINED','APPROVED','EXTENSION','DELETED') DEFAULT 'INVALID',
	`identificationdata_type_of_controller` ENUM ('NATURAL','LEGAL') DEFAULT 'NATURAL',
	`identificationdata_controller_name` VARCHAR(255) NOT NULL,
	`identificationdata_controller_address1` VARCHAR(100) NOT NULL,
	`identificationdata_controller_postalcode` VARCHAR(10) NOT NULL,
	`identificationdata_controller_city` VARCHAR(255) NOT NULL,
	`identificationdata_controller_regno` VARCHAR(50) NOT NULL,
	`identificationdata_controller_telephone` VARCHAR(100) NOT NULL,
	`identificationdata_controller_telefax` VARCHAR(100) NOT NULL,
	`identificationdata_controller_mail` VARCHAR(100) NOT NULL,
	`identificationdata_controller_website` VARCHAR(255) NOT NULL,
	`identificationdata_pocessor_name` VARCHAR(255) DEFAULT NULL,
	`identificationdata_pocessor_address1` VARCHAR(100) DEFAULT NULL,
	`identificationdata_pocessor_postalcode` VARCHAR(10) DEFAULT NULL,
	`identificationdata_pocessor_city` VARCHAR(255) DEFAULT NULL,
	`identificationdata_pocessor_telephone` VARCHAR(100) DEFAULT NULL,
	`identificationdata_pocessor_telefax` VARCHAR(100) DEFAULT NULL,
	`identificationdata_pocessor_mail` VARCHAR(100) DEFAULT NULL,
	`identificationdata_pocessor_operations` TEXT DEFAULT NULL,
	`identificationdata_place_name` VARCHAR(255) DEFAULT NULL,
	`identificationdata_place_address1` VARCHAR(100) DEFAULT NULL,
	`identificationdata_place_postalcode` VARCHAR(10) DEFAULT NULL,
	`identificationdata_place_city` VARCHAR(255) DEFAULT NULL,
	`purposes_purpose` TEXT,
	`purposes_established_by_law` TINYINT(1) DEFAULT 0,
	`purposes_established_by_law_description` TEXT,
	`purposes_established_by_consent` TINYINT(1) DEFAULT 0,
	`purposes_established_by_consent_description` TEXT,
	`sources_source_of_information` TEXT,
	`sources_source_medium` TEXT,
	`sources_manner_manual` TINYINT(1) DEFAULT 0,
	`sources_manner_automatic` TINYINT(1) DEFAULT 0,
	`datasubject_civil_servants` TINYINT(1) DEFAULT 0,
	`datasubject_clients` TINYINT(1) DEFAULT 0,
	`datasubject_employees` TINYINT(1) DEFAULT 0,
	`datasubject_members` TINYINT(1) DEFAULT 0,
	`datasubject_patients` TINYINT(1) DEFAULT 0,
	`datasubject_shareholders` TINYINT(1) DEFAULT 0,
	`datasubject_social_assistence_users` TINYINT(1) DEFAULT 0,
	`datasubject_students` TINYINT(1) DEFAULT 0,
	`datasubject_suppliers` TINYINT(1) DEFAULT 0,
	`datasubject_other` TEXT DEFAULT NULL,
	`personaldata_health` TINYINT(1) DEFAULT 0,
	`personaldata_political_opinions` TINYINT(1) DEFAULT 0,
	`personaldata_racial_origin` TINYINT(1) DEFAULT 0,
	`personaldata_religious_beliefs` TINYINT(1) DEFAULT 0,
	`personaldata_sexlife` TINYINT(1) DEFAULT 0,
	`personaldata_trade_union_membership` TINYINT(1) DEFAULT 0,
	`personaldata_biometric_data` TINYINT(1) DEFAULT 0,
	`personaldata_identification_data` TINYINT(1) DEFAULT 0,
	`personaldata_personal_detail_data` TINYINT(1) DEFAULT 0,
	`personaldata_address_detail_data` TINYINT(1) DEFAULT 0,
	`personaldata_residence_details` TINYINT(1) DEFAULT 0,
	`personaldata_video_surveillance` TINYINT(1) DEFAULT 0,
	`personaldata_economic_data` TINYINT(1) DEFAULT 0,
	`personaldata_professional_life` TINYINT(1) DEFAULT 0,
	`personaldata_audio` TINYINT(1) DEFAULT 0,
	`personaldata_photo` TINYINT(1) DEFAULT 0,
	`personaldata_other` TEXT DEFAULT NULL,
	`data_established_time` DATETIME,
	`data_storage_period` VARCHAR(255),
	`data_storage_legal_basis` VARCHAR(255),
	`data_storage_purpose` VARCHAR(255),
	`data_usage_period` VARCHAR(255),
	`data_usage_legal_basis` VARCHAR(255),
	`data_usage_purpose` VARCHAR(255),
	`data_usage_specification` VARCHAR(255),
	`data_details` TEXT DEFAULT NULL,
	`restriction_details` TEXT DEFAULT NULL,
	`restriction_legal_basis` TEXT DEFAULT NULL,
	`disclosure_enabled` TINYINT(1) DEFAULT 0,
	`disclosure_recipient` TEXT DEFAULT NULL,
	`disclosure_purpose` TEXT DEFAULT NULL,
	`transfer_enabled` TINYINT(1) DEFAULT 0,
	`transfer_country` VARCHAR(100),
	`transfer_recipient` VARCHAR(255),
	`transfer_foreign_user` VARCHAR(255),
	`transfer_purpose` VARCHAR(255),
	`transfer_legal_basis` VARCHAR(255),
	`transfer_frequency` ENUM ('ONCE','CONTINUOUSLY','PERIODICALLY'),
	`transfer_period` INT(3) DEFAULT NULL,
	`transfer_authorization` VARCHAR(255),
	`linkedsystem_enabled` TINYINT(1) DEFAULT 0,
	`linkedsystem_description` TEXT,
	`linkedsystem_notification` TEXT,
	`linkedsystem_authorization` VARCHAR(255),
	`security_confidentiality` TEXT,
	`security_integrity` TEXT,
	`security_availability` TEXT,
	`security_transparency_by_document` TINYINT(1) DEFAULT 0,
	`security_document_details` VARCHAR(100) DEFAULT NULL,
	`security_transparency_by_plan` TINYINT(1) DEFAULT 0,
	`security_plan_details` VARCHAR(100) DEFAULT NULL,
	`applicant_firstname` VARCHAR(100) DEFAULT NULL,
	`applicant_lastname` VARCHAR(100) DEFAULT NULL,
	`applicant_application_date` DATE,
	PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;





